CREATE TABLE Products(
 ProductID UNIQUEIDENTIFIER PRIMARY KEY, 
 ProductName VARCHAR(500) NOT NULL,
 ProductImage VARBINARY(MAX),
 ProductDetails VARCHAR  NOT NULL,
 ProductPrice SMALLMONEY NOT NULL,
 StockDate Date NOT NULL DEFAULT (GETDATE()),
 Stock INT NULL)